[files]
extend-exclude = [
    "src-tauri/src/camoufox/data/*.json",
    "src-tauri/src/camoufox/data/*.xml",
    "src/i18n/locales/pt.json",
    "src-tauri/build.rs",
    "src-tauri/tests/fixtures/test.ovpn",
]
